### ISSUE TITLE
Rspec.deprecate()'s API has changed.

### ISSUE THREAD

**Issue by voidus** [rodjek/rspec-puppet#245]
The commit https://github.com/rspec/rspec-core/commit/c07c4cf9b47b9f58b222b77ca13daea11b3d7585 changed the API of RSpec.deprecate().

When I try to run `rake rspec` in https://github.com/wyrie/puppet-backuppc/commit/acf4baafd45e8b554bdda29d9481d2e0898b3713, I get the following error:
```
Failures:

  1) backuppc::client On Ubuntu should include Class[backuppc::params]
     Failure/Error: it { should include_class("backuppc::params") }
     TypeError:
       no implicit conversion of Symbol into Hash
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/deprecation.rb:12:in `merge'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/deprecation.rb:12:in `deprecate'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/matchers/include_class.rb:7:in `block (2 levels) in <module:ManifestMatchers>'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-expectations-2.99.2/lib/rspec/matchers/extensions/instance_eval_with_args.rb:11:in `instance_exec'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-expectations-2.99.2/lib/rspec/matchers/extensions/instance_eval_with_args.rb:11:in `instance_eval_with_args'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-expectations-2.99.2/lib/rspec/matchers/matcher.rb:99:in `matches?'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-expectations-2.99.2/lib/rspec/expectations/handler.rb:24:in `handle_matcher'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/memoized_helpers.rb:77:in `should'
     # ./spec/classes/backuppc_client_spec.rb:17:in `block (3 levels) in <top (required)>'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:116:in `block in run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:248:in `with_around_each_hooks'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:113:in `run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:515:in `block in run_examples'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:511:in `map'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:511:in `run_examples'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:496:in `run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `block in run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `map'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `block (2 levels) in run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `map'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `block in run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/reporter.rb:58:in `report'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:21:in `run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
     # /home/voyd/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'
```

From a quick look at the code, I think that reverting 8d951da86be5e61e17fec4491cb2990b8efb590b might solve this. I'll have a better look.
