### ISSUE TITLE
Could not find class 

### ISSUE THREAD

**Issue by JWZH** [rodjek/rspec-puppet#395]
The is the module directory. 

```
➜   tree
.
├── Gemfile
├── Gemfile.lock
├── manifests
│   └── init.pp
├── metadata.json
├── Rakefile
├── README.md
├── spec
│   ├── classes
│   │   └── certs_spec.rb
│   ├── defines
│   ├── fixtures
│   │   ├── manifests
│   │   │   └── site.pp
│   │   └── modules
│   │       └── certs
│   │           └── manifests -> ../../../../manifests
│   ├── functions
│   ├── hosts
│   └── spec_helper.rb
└── tests
    └── init.pp

12 directories, 10 files
```

manifests/init.pp

```
class certs {}
```

spec/classes/certs_spec.rb

```
require 'spec_helper'

describe 'certs' do
  it { is_expected.to compile }
end
```

```
➜   rake rspec
/home/wjiang/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/wjiang/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.5.1/lib:/home/wjiang/.rvm/gems/ruby-2.1.5/gems/rspec-support-3.5.0/lib /home/wjiang/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
F

Failures:

  1) certs should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile }
       error during compilation: Evaluation Error: Error while evaluating a Function Call, Could not find class ::certs for wjiang.engineering.syd2.internal at line 1:1 on node wjiang.engineering.syd2.internal
     # ./spec/classes/certs_spec.rb:4:in `block (2 levels) in <top (required)>'

Finished in 0.10328 seconds (files took 0.53017 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/classes/certs_spec.rb:4 # certs should compile into a catalogue without dependency cycles

/home/wjiang/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/wjiang/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.5.1/lib:/home/wjiang/.rvm/gems/ruby-2.1.5/gems/rspec-support-3.5.0/lib /home/wjiang/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by cainj13** [comment]
exact same issue here.  Just to sanity check, I did this:

`puppet module generate jcain-demoError`

But when I run `rspec`,  I still get this:

>      # ------------------
>      # --- Caused by: ---
>      # Puppet::Error:
>      #   Could not find class ::demoerror for localhost.redhat.com
>      #   /home/jcain/.gem/ruby/gems/puppet-4.7.0/lib/puppet/parser/compiler.rb:382:in `block in evaluate_classes'

Here are some versions I'm running if that helps:

rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-helpers (1.2.0)
rspec-mocks (3.5.0)
rspec-puppet (2.4.0)
rspec-support (3.5.0)

**Comment by dandunckelman** [comment]
When you run `rake spec_prep`, it simply installs all the modules from `.fixtures.yml`.  So, could you share the content of your `.fixtures.yml`?  And is the missing module appearing in `spec/fixtures/modules/MODULE_NAME` as expected?

When you run `rake spec`, it deletes the modules from that folder as a cleanup phase.

**Comment by cainj13** [comment]
I seem to have the MODULE_NAME as expected, but I don't have a .fixtures.yml.  Is that a requirement?  rspec-puppet-init doesn't seem to add that file, do I need it?

```
demoError/
├── examples
│   └── init.pp
├── Gemfile
├── manifests
│   └── init.pp
├── metadata.json
├── Rakefile
├── README.md
└── spec
    ├── classes
    │   └── init_spec.rb
    ├── defines
    ├── fixtures
    │   ├── manifests
    │   │   └── site.pp
    │   └── modules
    │       └── demoError
    │           └── manifests -> ../../../../manifests
    ├── functions
    ├── hosts
    └── spec_helper.rb

12 directories, 9 files

```

**Comment by dandunckelman** [comment]
@cainj13 maybe `.fixtures.yml` isn't required.  I've always used it.  Here's one of mine:

```
fixtures:
  forge_modules:
    apache:
      ref: '1.10.0'
      repo: 'puppetlabs/apache'
    apt:
      ref: '2.3.0'
      repo: 'puppetlabs/apt'
    chocolatey:
      ref: '1.2.6'
      repo: 'chocolatey/chocolatey'
    concat:
      ref: '2.2.0'
      repo: 'puppetlabs/concat'
    download_file:
      ref: '2.0.0'
      repo: 'puppet/download_file'
    extlib:
      ref: '1.0.0'
      repo: 'puppet/extlib'
    logrotate:
      ref: '1.4.0'
      repo: 'yo61/logrotate'
    powershell:
      ref: '2.0.2'
      repo: 'puppetlabs/powershell'
    puppet:
      ref: '6.0.0'
      repo: 'theforeman/puppet'
    registry:
      ref: '1.1.3'
      repo: 'puppetlabs/registry'
    stdlib:
      ref: '4.12.0'
      repo: 'puppetlabs/stdlib'
    windows_env:
      ref: '2.2.2'
      repo: 'badgerious/windows_env'
  repositories:
    newrelic:
      branch: 'specify_windows_provider'
      repo: 'https://github.com/dandunckelman/puppet-newrelic'
    wsus_client:
      ref: '7fcc3b37a3ae665c2f8502081f904a3eea28b2a0'
      repo: 'https://github.com/puppetlabs/puppetlabs-wsus_client.git'
  symlinks:
    ta_base: "#{source_dir}"
    ta_linux: "#{source_dir}/../ta_linux"
    ta_windows: "#{source_dir}/../ta_windows"
```

So, you can see how this can be helpful in testing various version of modules as well as specifying specific commit hashes or branches.

Could you share the `*_spec.rb` you're running?
